module.exports = [
    {
      city: "Paris", 
      lng: "48.8567", 
      lat: "2.3522", 
      country: "France", 
      iso2: "FR", 
      admin_name: "Île-de-France", 
      capital: "primary", 
      population: "11060000", 
      population_proper: "2148271"
    }, 
    {
      city: "Marseille", 
      lng: "43.2964", 
      lat: "5.3700", 
      country: "France", 
      iso2: "FR", 
      admin_name: "Provence-Alpes-Côte d’Azur", 
      capital: "admin", 
      population: "870731", 
      population_proper: "870731"
    }, 
    {
      city: "Lyon",
      lng: 45.7600,
      lat: 4.8400,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "admin",
      population: 522969,
      population_proper: 522969
    },
    {
      city: "Toulouse",
      lng: 43.6045,
      lat: 1.4440,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "admin",
      population: 493465,
      population_proper: 493465
    },    
    {
      city: "Nice",
      lng: 43.7034,
      lat: 7.2663,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "minor",
      population: 342669,
      population_proper: 342669
    },
    {
      city: "Nantes",
      lng: 47.2181,
      lat: -1.5528,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "admin",
      population: 318808,
      population_proper: 318808
    },
    {
      city: "Montpellier",
      lng: 43.6119,
      lat: 3.8772,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "minor",
      population: 295542,
      population_proper: 295542
    },
    {
      city: "Strasbourg",
      lng: 48.5833,
      lat: 7.7458,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "admin",
      population: 290576,
      population_proper: 290576
    },
    {
      city: "Bordeaux",
      lng: 44.8400,
      lat: -0.5800,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "admin",
      population: 260958,
      population_proper: 260958
    },
    {
      city: "Lille",
      lng: 50.6278,
      lat: 3.0583,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "admin",
      population: 234475,
      population_proper: 234475
    },
    {
      city: "Rennes",
      lng: 48.1147,
      lat: -1.6794,
      country: "France",
      iso2: "FR",
      admin_name: "Bretagne",
      capital: "admin",
      population: 220488,
      population_proper: 220488
    },
    {
      city: "Reims",
      lng: 49.2628,
      lat: 4.0347,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 182211,
      population_proper: 181194
    },
    {
      city: "Toulon",
      lng: 43.1258,
      lat: 5.9306,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "minor",
      population: 178745,
      population_proper: 178745
    },
    {
      city: "Saint-Étienne",
      lng: 45.4347,
      lat: 4.3903,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 173821,
      population_proper: 173821
    },
    {
      city: "Le Havre",
      lng: 49.4900,
      lat: 0.1000,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "minor",
      population: 169733,
      population_proper: 168290
    },
    {
      city: "Grenoble",
      lng: 45.1715,
      lat: 5.7224,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 158198,
      population_proper: 158198
    },
    {
      city: "Dijon",
      lng: 47.3167,
      lat: 5.0167,
      country: "France",
      iso2: "FR",
      admin_name: "Bourgogne-Franche-Comté",
      capital: "admin",
      population: 158002,
      population_proper: 158002
    },
    {
      city: "Angers",
      lng: 47.4736,
      lat: -0.5542,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "minor",
      population: 155850,
      population_proper: 155850
    },
    {
      city: "Villeurbanne",
      lng: 45.7667,
      lat: 4.8803,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 152212,
      population_proper: 152212
    },    
    {
      city: "Nîmes",
      lng: 43.8380,
      lat: 4.3610,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "minor",
      population: 149633,
      population_proper: 148561
    },
    {
      city: "Clermont-Ferrand",
      lng: 45.7831,
      lat: 3.0824,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 147865,
      population_proper: 147865
    },
    {
      city: "Aix-en-Provence",
      lng: 43.5263,
      lat: 5.4454,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "minor",
      population: 145133,
      population_proper: 145133
    },
    {
      city: "Le Mans",
      lng: 48.0077,
      lat: 0.1984,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "minor",
      population: 143847,
      population_proper: 143847
    },
    {
      city: "Brest",
      lng: 48.3900,
      lat: -4.4900,
      country: "France",
      iso2: "FR",
      admin_name: "Bretagne",
      capital: "minor",
      population: 139926,
      population_proper: 139926
    },
    {
      city: "Tours",
      lng: 47.3936,
      lat: 0.6892,
      country: "France",
      iso2: "FR",
      admin_name: "Centre-Val de Loire",
      capital: "minor",
      population: 137087,
      population_proper: 137087
    },
    {
      city: "Amiens",
      lng: 49.8920,
      lat: 2.2990,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 134706,
      population_proper: 134706
    },
    {
      city: "Limoges",
      lng: 45.8353,
      lat: 1.2625,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 131479,
      population_proper: 130876
    },
    {
      city: "Annecy",
      lng: 45.9160,
      lat: 6.1330,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 130721,
      population_proper: 130721
    },     
    {
      city: "Perpignan",
      lng: 42.6986,
      lat: 2.8956,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "minor",
      population: 119344,
      population_proper: 119344
    },
    {
      city: "Metz",
      lng: 49.1203,
      lat: 6.1778,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 118489,
      population_proper: 118489
    },
    {
      city: "Besançon",
      lng: 47.2400,
      lat: 6.0200,
      country: "France",
      iso2: "FR",
      admin_name: "Bourgogne-Franche-Comté",
      capital: "minor",
      population: 118258,
      population_proper: 118258
    },
    {
      city: "Orléans",
      lng: 47.9025,
      lat: 1.9090,
      country: "France",
      iso2: "FR",
      admin_name: "Centre-Val de Loire",
      capital: "admin",
      population: 116269,
      population_proper: 116269
    },
    {
      city: "Rouen",
      lng: 49.4428,
      lat: 1.0886,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "admin",
      population: 112321,
      population_proper: 112321
    },
    {
      city: "Mulhouse",
      lng: 47.7500,
      lat: 7.3400,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 108942,
      population_proper: 108312
    },
    {
      city: "Caen",
      lng: 49.1800,
      lat: -0.3700,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "minor",
      population: 106230,
      population_proper: 106230
    },
    {
      city: "Nancy",
      lng: 48.6936,
      lat: 6.1846,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 105058,
      population_proper: 105058
    },
    {
      city: "Roubaix",
      lng: 50.6901,
      lat: 3.1817,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 98828,
      population_proper: 98828
    },     
    {
      city: "Tourcoing",
      lng: 50.7239,
      lat: 3.1612,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 98656,
      population_proper: 98656
    },
    {
      city: "Poitiers",
      lng: 46.5800,
      lat: 0.3400,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 89212,
      population_proper: 89212
    },
    {
      city: "Dunkerque",
      lng: 51.0383,
      lat: 2.3775,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 86865,
      population_proper: 86279
    },
    {
      city: "Versailles",
      lng: 48.8053,
      lat: 2.1350,
      country: "France",
      iso2: "FR",
      admin_name: "Île-de-France",
      capital: "minor",
      population: 85205,
      population_proper: 84808
    },
    {
      city: "La Rochelle",
      lng: 46.1600,
      lat: -1.1500,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 77205,
      population_proper: 77205
    },
    {
      city: "Pau",
      lng: 43.3000,
      lat: -0.3700,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 76275,
      population_proper: 75627
    }, 
    {
      city: "Cannes",
      lng: 43.5513,
      lat: 7.0128,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 74545,
      population_proper: 74545
    },
    {
      city: "Antibes",
      lng: 43.5808,
      lat: 7.1239,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 73438,
      population_proper: 73438
    },
    {
      city: "Calais",
      lng: 50.9481,
      lat: 1.8564,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 72929,
      population_proper: 72509
    },
    {
      city: "Mérignac",
      lng: 44.8386,
      lat: -0.6436,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 72197,
      population_proper: 72197
    },
    {
      city: "Saint-Nazaire",
      lng: 47.2736,
      lat: -2.2139,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "minor",
      population: 71394,
      population_proper: 71394
    },
    {
      city: "Ajaccio",
      lng: 41.9267,
      lat: 8.7369,
      country: "France",
      iso2: "FR",
      admin_name: "Corsica",
      capital: "admin",
      population: 71361,
      population_proper: 71361
    },
     {
      city: "Vénissieux",
      lng: 45.6978,
      lat: 4.8867,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 67285,
      population_proper: 67285
    },
    {
      city: "Pessac",
      lng: 44.8067,
      lat: -0.6311,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 65245,
      population_proper: 65245
    },
    {
      city: "Valence",
      lng: 44.9333,
      lat: 4.8917,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 64749,
      population_proper: 64749
    },     
    {
      city: "La Seyne-sur-Mer",
      lng: 43.1000,
      lat: 5.8830,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 62987,
      population_proper: 62987
    },
    {
      city: "Troyes",
      lng: 48.2997,
      lat: 4.0792,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 61996,
      population_proper: 61957
    },
    {
      city: "Cherbourg",
      lng: 49.6333,
      lat: -1.6000,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "minor",
      population: 60991,
      population_proper: 25370
    },
    {
      city: "Chambéry",
      lng: 45.5700,
      lat: 5.9118,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 58917,
      population_proper: 58917
    },
    {
      city: "Lorient",
      lng: 47.7500,
      lat: -3.3600,
      country: "France",
      iso2: "FR",
      admin_name: "Bretagne",
      capital: "minor",
      population: 57246,
      population_proper: 57246
    },
    {
      city: "Beauvais",
      lng: 49.4303,
      lat: 2.0952,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 57071,
      population_proper: 57071
    },
    {
      city: "Saint-Quentin",
      lng: 49.8486,
      lat: 3.2864,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 53856,
      population_proper: 53570
    },
    {
      city: "Vannes",
      lng: 47.6559,
      lat: -2.7603,
      country: "France",
      iso2: "FR",
      admin_name: "Bretagne",
      capital: "minor",
      population: 53719,
      population_proper: 53719
    },
    {
      city: "Vaulx-en-Velin",
      lng: 45.7768,
      lat: 4.9186,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 52795,
      population_proper: 52795
    },
    {
      city: "Cagnes-sur-Mer",
      lng: 43.6644,
      lat: 7.1489,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 52178,
      population_proper: 52178
    },     
    {
      city: "Bayonne",
      lng: 43.4900,
      lat: -1.4800,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 51894,
      population_proper: 51894
    },
    {
      city: "Laval",
      lng: 48.0733,
      lat: -0.7689,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "minor",
      population: 49733,
      population_proper: 49733
    },
    {
      city: "Bastia",
      lng: 42.7008,
      lat: 9.4503,
      country: "France",
      iso2: "FR",
      admin_name: "Corsica",
      capital: "",
      population: 48503,
      population_proper: 48503
    },
    {
      city: "Saint-Herblain",
      lng: 47.2122,
      lat: -1.6497,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "",
      population: 47415,
      population_proper: 47415
    },
    {
      city: "Belfort",
      lng: 47.6400,
      lat: 6.8500,
      country: "France",
      iso2: "FR",
      admin_name: "Bourgogne-Franche-Comté",
      capital: "minor",
      population: 46954,
      population_proper: 46443
    },
    {
      city: "Saint-Priest",
      lng: 45.6972,
      lat: 4.9447,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 46927,
      population_proper: 46927
    },
    {
      city: "Évreux",
      lng: 49.0200,
      lat: 1.1500,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "minor",
      population: 46707,
      population_proper: 46349
    },
    {
      city: "Charleville-Mézières",
      lng: 49.7719,
      lat: 4.7161,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 46436,
      population_proper: 46436
    },
    {
      city: "Chalon-sur-Saône",
      lng: 46.7806,
      lat: 4.8528,
      country: "France",
      iso2: "FR",
      admin_name: "Bourgogne-Franche-Comté",
      capital: "minor",
      population: 45056,
      population_proper: 45056
    },
    {
      city: "Châlons-en-Champagne",
      lng: 48.9575,
      lat: 4.3650,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "minor",
      population: 44379,
      population_proper: 44379
    },
    {
      city: "Saint-Brieuc",
      lng: 48.5136,
      lat: -2.7653,
      country: "France",
      iso2: "FR",
      admin_name: "Bretagne",
      capital: "minor",
      population: 44170,
      population_proper: 43605
    },
    {
      city: "Sète",
      lng: 43.4053,
      lat: 3.6975,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "",
      population: 43858,
      population_proper: 43858
    },
    {
      city: "Talence",
      lng: 44.8000,
      lat: -0.5840,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 43820,
      population_proper: 43820
    },
    {
      city: "Châteauroux",
      lng: 46.8103,
      lat: 1.6911,
      country: "France",
      iso2: "FR",
      admin_name: "Centre-Val de Loire",
      capital: "minor",
      population: 43442,
      population_proper: 43122
    },
    {
      city: "Valenciennes",
      lng: 50.3581,
      lat: 3.5233,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 43405,
      population_proper: 43229
    },
    {
      city: "Caluire-et-Cuire",
      lng: 45.7953,
      lat: 4.8472,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 43294,
      population_proper: 43294
    },
    {
      city: "Rezé",
      lng: 47.1917,
      lat: -1.5694,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "",
      population: 42919,
      population_proper: 42919
    },
    {
      city: "Tarbes",
      lng: 43.2300,
      lat: 0.0700,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "minor",
      population: 42758,
      population_proper: 42758
    },
    {
      city: "Bron",
      lng: 45.7394,
      lat: 4.9139,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 42244,
      population_proper: 42244
    },
    {
      city: "Le Cannet",
      lng: 43.5769,
      lat: 7.0194,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 41887,
      population_proper: 41887
    },
    {
      city: "Alès",
      lng: 44.1281,
      lat: 4.0817,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "minor",
      population: 41837,
      population_proper: 41837
    },
    {
      city: "Angoulême",
      lng: 45.6500,
      lat: 0.1600,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 41711,
      population_proper: 41603
    },
    {
      city: "Arras",
      lng: 50.2920,
      lat: 2.7800,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 41694,
      population_proper: 41694
    },     
    {
      city: "Bourg-en-Bresse",
      lng: 46.2056,
      lat: 5.2289,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 41248,
      population_proper: 41111
    },
    {
      city: "Wattrelos",
      lng: 50.7000,
      lat: 3.2170,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 40898,
      population_proper: 40898
    },
    {
      city: "Boulogne-sur-Mer",
      lng: 50.7264,
      lat: 1.6147,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 40664,
      population_proper: 40251
    },
    {
      city: "Colomiers",
      lng: 43.6139,
      lat: 1.3367,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "",
      population: 39968,
      population_proper: 39968
    },
    {
      city: "Anglet",
      lng: 43.4850,
      lat: -1.5183,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 39719,
      population_proper: 39719
    },
    {
      city: "Douai",
      lng: 50.3714,
      lat: 3.0800,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 39634,
      population_proper: 39613
    },
    {
      city: "Marcq-en-Baroeul",
      lng: 50.6711,
      lat: 3.0972,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 38570,
      population_proper: 38486
    },
    {
      city: "Chartres",
      lng: 48.4560,
      lat: 1.4840,
      country: "France",
      iso2: "FR",
      admin_name: "Centre-Val de Loire",
      capital: "minor",
      population: 38534,
      population_proper: 38534
    },
    {
      city: "Saint-Martin-d’Hères",
      lng: 45.1672,
      lat: 5.7653,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 38398,
      population_proper: 37935
    },
    {
      city: "Échirolles",
      lng: 45.1436,
      lat: 5.7183,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 36961,
      population_proper: 36932
    },
    {
      city: "Villenave-d’Ornon",
      lng: 44.7806,
      lat: -0.5658,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 36754,
      population_proper: 36754
    },
    {
      city: "Annemasse",
      lng: 46.1958,
      lat: 6.2364,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 36396,
      population_proper: 36396
    },
    {
      city: "Creil",
      lng: 49.2597,
      lat: 2.4731,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 36304,
      population_proper: 36304
    },     
    {
      city: "Thonon-les-Bains",
      lng: 46.3627,
      lat: 6.4750,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 35826,
      population_proper: 35826
    },
    {
      city: "Montluçon",
      lng: 46.3408,
      lat: 2.6033,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 34938,
      population_proper: 34361
    },
    {
      city: "Meyzieu",
      lng: 45.7667,
      lat: 5.0036,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      population: 34640,
      population_proper: 34640
    },
    {
      city: "Roanne",
      lng: 46.0367,
      lat: 4.0689,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 34004,
      population_proper: 33809
    },
    {
      city: "Schiltigheim",
      lng: 48.6078,
      lat: 7.7500,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      population: 33993,
      population_proper: 33993
    },
    {
      city: "Nevers",
      lng: 46.9933,
      lat: 3.1572,
      country: "France",
      iso2: "FR",
      admin_name: "Bourgogne-Franche-Comté",
      capital: "minor",
      population: 33279,
      population_proper: 33005
    },
    {
      city: "Agen",
      lng: 44.2049,
      lat: 0.6212,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 33012,
      population_proper: 32602
    },
    {
      city: "Cambrai",
      lng: 50.1767,
      lat: 3.2356,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 32501,
      population_proper: 32176
    },
    {
      city: "Lens",
      lng: 50.4322,
      lat: 2.8333,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 31606,
      population_proper: 31461
    },
    {
      city: "Rillieux-la-Pape",
      lng: 45.8214,
      lat: 4.8983,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      population: 30697,
      population_proper: 30697
    },
    {
      city: "Bègles",
      lng: 44.8086,
      lat: -0.5478,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      population: 30642,
      population_proper: 30642
    },
    {
      city: "Menton",
      lng: 43.7750,
      lat: 7.5000,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      population: 30525,
      population_proper: 30525
    },
    {
      city: "Aix-les-Bains",
      lng: 45.6885,
      lat: 5.9153,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      population: 30463,
      population_proper: 30463
    },
    {
      city: "Liévin",
      lng: 50.4228,
      lat: 2.7786,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      population: 30423,
      population_proper: 30112
    },         
    {
      city: "Périgueux",
      lng: 45.1929,
      lat: 0.7217,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "minor",
      population: 30060,
      population_proper: 29896
    },
    {
      city: "Vandœuvre-lès-Nancy",
      lng: 48.6567,
      lat: 6.1683,
      country: "France",
      iso2: "FR",
      admin_name: "Grand Est",
      capital: "",
      population: 30009,
      population_proper: 29942
    },
    {
      city: "Maubeuge",
      lng: 50.2775,
      lat: 3.9734,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 29632,
      population_proper: 29589
    },
    {
      city: "Saint-Laurent-du-Var",
      lng: 43.6680,
      lat: 7.1880,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 29169,
      population_proper: 29169
    },
    {
      city: "Sotteville-lès-Rouen",
      lng: 49.4092,
      lat: 1.0900,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "",
      population: 29068,
      population_proper: 29068
    },
    {
      city: "Décines-Charpieu",
      lng: 45.7694,
      lat: 4.9594,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 28930,
      population_proper: 28930
    },
    {
      city: "Soissons",
      lng: 49.3817,
      lat: 3.3236,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 28712,
      population_proper: 28712
    },
    {
      city: "Dieppe",
      lng: 49.9200,
      lat: 1.0800,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "minor",
      population: 28561,
      population_proper: 28241
    },
    {
      city: "Saint-Étienne-du-Rouvray",
      lng: 49.3786,
      lat: 1.1050,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "",
      population: 28500,
      population_proper: 28352
    },
    {
      city: "Tournefeuille",
      lng: 43.5853,
      lat: 1.3442,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "",
      population: 28117,
      population_proper: 28117
    },
    {
      city: "Saint-Sébastien-sur-Loire",
      lng: 47.2081,
      lat: -1.5014,
      country: "France",
      iso2: "FR",
      admin_name: "Pays de la Loire",
      capital: "",
      population: 27493,
      population_proper: 27493
    },
    {
      city: "Lambersart",
      lng: 50.6500,
      lat: 3.0250,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 27415,
      population_proper: 27400
    },
    {
      city: "Vallauris",
      lng: 43.5805,
      lat: 7.0538,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 27364,
      population_proper: 27364
    },
    {
      city: "Oullins",
      lng: 45.7150,
      lat: 4.8083,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 26583,
      population_proper: 26553
    },
    {
      city: "Le Grand-Quevilly",
      lng: 49.4072,
      lat: 1.0531,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "",
      population: 25963,
      population_proper: 25963
    },
    {
      city: "Alençon",
      lng: 48.4306,
      lat: 0.0931,
      country: "France",
      iso2: "FR",
      admin_name: "Normandie",
      capital: "minor",
      population: 25870,
      population_proper: 25870
    },
    {
      city: "Montbéliard",
      lng: 47.5100,
      lat: 6.8000,
      country: "France",
      iso2: "FR",
      admin_name: "Bourgogne-Franche-Comté",
      capital: "minor",
      population: 25809,
      population_proper: 25806
    },
    {
      city: "Biarritz",
      lng: 43.4800,
      lat: -1.5600,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 25787,
      population_proper: 25787
    },
    {
      city: "Gradignan",
      lng: 44.7725,
      lat: -0.6156,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 25694,
      population_proper: 25694
    },
    {
      city: "Blagnac",
      lng: 43.6364,
      lat: 1.3906,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "",
      population: 25525,
      population_proper: 25525
    },
    {
      city: "La Garde",
      lng: 43.1256,
      lat: 6.0108,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 25505,
      population_proper: 25505
    },
    {
      city: "Cenon",
      lng: 44.8578,
      lat: -0.5317,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 25496,
      population_proper: 25496
    },
    {
      city: "Béthune",
      lng: 50.5303,
      lat: 2.6408,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "minor",
      population: 25193,
      population_proper: 25039
    },
    {
      city: "Vichy",
      lng: 46.1278,
      lat: 3.4267,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "minor",
      population: 24980,
      population_proper: 24980
    },
    {
      city: "Armentières",
      lng: 50.6881,
      lat: 2.8811,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 24909,
      population_proper: 24909
    },
    {
      city: "Eysines",
      lng: 44.8853,
      lat: -0.6500,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 24488,
      population_proper: 24488
    },
    {
      city: "Rodez",
      lng: 44.3506,
      lat: 2.5750,
      country: "France",
      iso2: "FR",
      admin_name: "Occitanie",
      capital: "minor",
      population: 24475,
      population_proper: 24475
    },
    {
      city: "La Valette-du-Var",
      lng: 43.1383,
      lat: 5.9831,
      country: "France",
      iso2: "FR",
      admin_name: "Provence-Alpes-Côte d’Azur",
      capital: "",
      population: 24087,
      population_proper: 24087
    },
    {
      city: "Le Bouscat",
      lng: 44.8651,
      lat: -0.5996,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 23924,
      population_proper: 23890
    },
    {
      city: "Fontaine",
      lng: 45.1939,
      lat: 5.6856,
      country: "France",
      iso2: "FR",
      admin_name: "Auvergne-Rhône-Alpes",
      capital: "",
      population: 23211,
      population_proper: 23211
    },
    {
      city: "Lormont",
      lng: 44.8792,
      lat: -0.5217,
      country: "France",
      iso2: "FR",
      admin_name: "Nouvelle-Aquitaine",
      capital: "",
      population: 23181,
      population_proper: 23181
    },
    {
      city: "Loos",
      lng: 50.6128,
      lat: 3.0144,
      country: "France",
      iso2: "FR",
      admin_name: "Hauts-de-France",
      capital: "",
      population: 22866,
      population_proper: 22866
    },
    
  ]