module.exports.descriptors = [

    'Forêt',
    'Ancienne',
    'Pétrifiée',
    'Enchanté',
    'Cascade',
    'Émeraude',
    'Silencieuse',
    'Séquoia',
    'Grenouille Solitaire',
    'Érable',
    'Brumeuse',
    'Papillon',
    'Saphir',
    'Bourgeon',
    'Effervescent',
    'Doux-amer',
    'Océan',
    'Mélodie',
    'Mer',
    'Ciel',
    'Poussiéreux',
    'Diamant',
    'Hibou',
    'Éblouissant',
    'Incandescent',
    'Infini',
    'Enivrant',
    'Ensoleillé',
    'Magique',
    'Enjôleur'
  ];
  
  module.exports.places = [

    'Plaines',
    'Village',
    'Vallée',
    'Étang',
    'Camp de Groupe',
    'Camp Equestre',
    'Ville Fantôme',
    'Camp',
    'Hameau Abandonné',
    'Arrière-Pays',
    'Rivière',
    'Ruisseau',
    'Bord de Ruisseau',
    'Baie',
    'Source',
    'Bord de Baie',
    'Sables',
    'Camp de Mules',
    'Camp de Chasse',
    'Falaises',
    'Creux',
    'Pâturage',
    'Cap',
    'Dunes',
    'Escarpements',
  ];
  